twisters: 好记性不如烂笔头
search: 如果做人没有没人梦想,那么和咸鱼有什么区别.


menu:
  主页: /
  诗词: /poetry-and-song
  钱戏: /money-and-games
  项目: /projects
  文档: /docs
  归档: /archives
  标签: /tags
  图片: /images
  碎语: /whispers
  友链: /friends
  关于: /about
